name: plex-gostream

services:
  plex_gostream:
    build:
      context: ..
      dockerfile: docker/Dockerfile.plex
    container_name: plex-gostream
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    environment:
      - TZ=Etc/UTC
      - PLEX_CLAIM=
      - ADVERTISE_IP=http://192.168.0.144:32401/
      - MKV_PROXY_CONFIG_PATH=/config/config.json
      - GOSTREAM_ROOT_PATH=/config/gostream
      - GOSTREAM_SOURCE_PATH=/mnt/gostream-mkv-real
      - GOSTREAM_MOUNT_PATH=/mnt/gostream-mkv-virtual
      - GOSTREAM_STATE_DIR=/config/gostream/STATE
      - GOSTREAM_LOG_DIR=/config/gostream/logs
      - HEALTH_MONITOR_PORT=8095
      - GOSTREAM_HEALTH_MONITOR_ENABLED=1
    ports:
      - 32401:32400/tcp
      - 8090:8090
      - 8095:8095
      - 8096:8096
    volumes:
      - plex_config:/config
      - plex_transcode:/transcode
      - type: bind
        source: "B:/Documents/Docker Stuff/gostream-mkv-real"
        target: /mnt/gostream-mkv-real
      - type: bind
        source: "P:/Popcorn Time"
        target: /data/popcorn-time
      - type: bind
        source: "B:/Documents/Docker Stuff/gostream-mkv-real/config/config.json"
        target: /config/config.json

volumes:
  plex_config:
  plex_transcode:
